# Generated by Django 5.1.2 on 2024-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('MDL', 'Mdl'), ('EUR', 'Eur')], default='MDL', max_length=3)),
            ],
            options={
                'db_table': 'laptops',
            },
        ),
    ]
