# Generated by Django 5.1.2 on 2024-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='link',
            field=models.CharField(default='darwin.md/laptopuri', max_length=255),
        ),
    ]
