# Generated by Django 5.1.2 on 2024-10-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_laptop_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='link',
        ),
    ]
